### ISSUE TITLE
Could not find a matching version of package utilities-php/routing

### ISSUE THREAD

**Issue by nauxxyzn** [utilities-php/router#2]
cannot run: composer require utilities-php/routing
package utilities-php/routing also not available at packagist.org

![image](https://user-images.githubusercontent.com/66082449/191652752-e769e171-70f5-4378-b37a-3d62c8ee1124.png)

**Comment by shahradelahi** [comment]
Yesterday I was doing some refactoring and completely forgot to review the Packagist.
I have just published the package. Please try again.

**Comment by nauxxyzn** [comment]
Thank you, looks good now.
I'll try ur library, hope work like a charm with my project 😄
